### ISSUE TITLE
tester ตรวจสอบความสมบูรณ์ของเกมเวอร์ชั่นแรก

### ISSUE THREAD

**Issue by SUPATKN** [Piicharpa/scratch-project-001#10]
เดี๋ยวเราจะลองให้เทสเล่นเกมคร่าวๆดูว่าเจอปัญหาอะไรไหม เดี๋ยวถ้าตัวเกมขั้นแรกเสร็จจะส่งให้

**Comment by SUPATKN** [comment]
https://scratch.mit.edu/projects/731341658 @kittisak101 @ChonlakornBoom tester เอาไปลองเล่นดูนะถ้ามีบัคตรงไหนเขียนได้เลย ลองเทสเล่นดูหลายๆรอบ ลองผ่านด่าน ลองทำให้ตัวละครเลือดหมดดู (ละก็วิธีชนะดูในรูปเดินเข้าไปประตูตรงนี้คือจะผ่านด่าน)  ปล.ถ้าจะเดินอย่าลืมเปลี่ยนภาษาเป็น Eng นะเดี๋ยวเดินไม่ไป
![วิธีชนะ](https://user-images.githubusercontent.com/110968387/189907057-ce181040-ab8e-46a9-a9f1-f857992de5e1.png)

**Comment by kittisak101** [comment]
ทำไมมันหันหน้าไม่ได้อะ

**Comment by SUPATKN** [comment]
อ้อโทษๆลืมบอกๆ หั่นใช้ลูกศรซ้ายขวา กด spacebar วิ่งนะ

**Comment by kittisak101** [comment]
มอนมันสุ่มเกิดหรอ บางตาวิ่งทั้วแมพละยังไม่เจอมอนเลย

**Comment by kittisak101** [comment]
เวลากด spacebar วิ่งอะมันเหมือนใช้ได้แต่กับเดินหน้า
เวลาเดินซ้าย,ขวา,ถ้อยหลัง แล้วกดวิ่งด้วยมันจะไปข้างหน้าอะ
(หรือมันต้องเป็นแบบนั้นอยู่แล้วอะ)

**Comment by SUPATKN** [comment]
อันนี่ตั้งใจให้เป็นแบบนี้อยู่แล้วๆ ละก็มอนสุ่มเกิดแต่ถ้าบางตาไม่เจอเดี๋ยวไว้ไปดูอีกที

**Comment by kittisak101** [comment]
ซ้ายขวาดีละ แต่ตอนถอยหลังน่าจะต้องเปลี่ยนหน่อยเพราะ ถอยแล้วกดวิ่งมันกลายเป็นเดินหน้าช้าๆอะมันไม่ได้เดินถอย

**Comment by SUPATKN** [comment]
อ้อออโอเคๆได้ๆ

**Comment by SUPATKN** [comment]
ตอนนี้แก้วิ่งกับถอยได้ละ เวลาถอย+กดวิ่งจะไม่เป็นแบบนั้นละ จะถอยอย่างเดียวเลย 
![image](https://user-images.githubusercontent.com/110968387/190412279-4f9e9fe2-63cb-431f-b798-538eaca37e6d.png)

**Comment by SUPATKN** [comment]
ตอนนี้แก้บัคตัวมอนไม่เกิดได้ละ เดี๋ยวจะส่งให้เทสอีกที 
(ที่ต้องแก้คือตรงนี้ของตัว player)
![image](https://user-images.githubusercontent.com/110968387/190412200-3ed007ac-5f9e-4815-9804-7f7d0ac0ead3.png)

**Comment by SUPATKN** [comment]
https://scratch.mit.edu/projects/731341658 @kittisak101 @ChonlakornBoom  เทสได้เลยๆ พวกระบบดาวกับประตูหลอกยังไม่ได้ทำนะ

**Comment by SUPATKN** [comment]
ขอตัดเสาสองต้นนี้ออกนะ เพราะบางทีมอนมันไปกองติดตรงนั้นเลยเอาออกดีกว่า 
![image](https://user-images.githubusercontent.com/110968387/190590210-088c4cc2-cc5d-48e4-a9f3-60062738006c.png)
