### ISSUE TITLE
ระบบดาว

### ISSUE THREAD

**Issue by SUPATKN** [Piicharpa/scratch-project-001#11]
ของ 15 ชิ้น
- ถ้าได้เก็บของได้ 5 ชิ้นได้ดาวเดียว
ถ้าได้เก็บของได้ 10 ชิ้นได้สองดาว
ถ้าได้เก็บของได้ครบทุกชิ้นได้สามดาว

**Comment by SUPATKN** [comment]
ตอนนี้ทำระบบดาวเสร็จละนะ 
![image](https://user-images.githubusercontent.com/110968387/190589825-78f26af2-9bae-4b78-8c7c-cb1d25a9b07e.png)

**Comment by SUPATKN** [comment]
https://scratch.mit.edu/projects/731341658 ลองเอาไปเทสระบบดาวดูนะ เก็บของละก็เข้าจุด finish ที่เดิมเลย ถ้าไม่มีบัคอะไรพิมบอกเลยนะจะได้ close issue @kittisak101 @ChonlakornBoom

**Comment by kittisak101** [comment]
ใช่ได้okละ

**Comment by kittisak101** [comment]
ไม่เจอบัคอะไรนะเท่าที่เล่นมา

**Comment by SUPATKN** [comment]
โอเคเลย
