### ISSUE TITLE
tester เทสเกมที่สมบูรณ์

### ISSUE THREAD

**Issue by SUPATKN** [Piicharpa/scratch-project-001#13]

**Comment by SUPATKN** [comment]
ตอนนี้เกมเสร็จละ ลองเทสดูเด้อมีต้องไหนบัคบ้าง @kittisak101 @ChonlakornBoom https://scratch.mit.edu/projects/731341658

**Comment by kittisak101** [comment]
ไม่เจอบัคนะ รอบูมconfirmอีกที

**Comment by ChonlakornBoom** [comment]
ยังไม่เจอบัคอะไร แต่ตรง How to play หมวด control น่าจะเพิ่มปุ่ม Space bar ด้วย

**Comment by SUPATKN** [comment]
เคๆ จะเพิ่มอยู่ลืมๆ55555
