### ISSUE TITLE
การทำมุมอง 3d เหลือใส่ texture กำแพง+เพดานกับพื้น

### ISSUE THREAD

**Issue by SUPATKN** [Piicharpa/scratch-project-001#3]
![300286632_3357016387851630_1586887869564374050_n](https://user-images.githubusercontent.com/110968387/188662599-f9556b88-a1a1-469a-b787-e2110e1336cc.png)

**Comment by kittisak101** [comment]
![background001](https://user-images.githubusercontent.com/110956091/189016077-1d141b67-acbc-496d-a37d-ca9c76f088a6.jpg)
![background002](https://user-images.githubusercontent.com/110956091/189016131-d65b067c-ee8b-4f3d-94c0-422a16e2f418.jpg)

**Comment by SUPATKN** [comment]
ตอนนี้ลองใส่ texture ดูละ น่าจะต้องทำขนาดรูปเป็น 100x100 pixels นะ @kittisak101 
เดี๋ยวรอด่านทุกอย่างเสร็จละจะเอา texture ไปใส่ในเกมละ
![image](https://user-images.githubusercontent.com/110968387/189162988-0d668099-3995-4341-bf61-699de4fcca9f.png)

**Comment by kittisak101** [comment]
เราทำได้แค่100x102 pixel อะ
![background0001](https://user-images.githubusercontent.com/110956091/189178341-806667fd-46c6-4f3a-af59-f41f6bca4c32.jpg)
![background0002](https://user-images.githubusercontent.com/110956091/189178356-c7d0ce9f-5baf-498b-a12b-dac7e5a72a13.jpg)

**Comment by SUPATKN** [comment]
โอเคๆ ได้เหมือนกัน

**Comment by SUPATKN** [comment]
อันนี้ทำกำแพงนะแปะไว้ก่อนเดี๋ยวกลับมาทำต่อ https://scratch.mit.edu/projects/729578615

**Comment by SUPATKN** [comment]
ตอนนี้ใส่ประตูของจริงกับประตูหลอกละ texture เกมคือเสร็จละ
![image](https://user-images.githubusercontent.com/110968387/189901732-81e10fbd-787d-4efe-bf6b-f27796121f16.png)
