### ISSUE TITLE
การทำให้ตัวละครหันโดยใช้เมาส์

### ISSUE THREAD

**Issue by SUPATKN** [Piicharpa/scratch-project-001#5]
ตอนนี้ทำให้ตัวละครหันโดยใช้เมาส์ได้แล้วแต่ยังมีบัคอยู่

![301528744_603062264612203_225494634243348739_n](https://user-images.githubusercontent.com/110968387/188670778-7bd5bf2d-87e5-4ae4-9b95-faa8fc56a0af.png)

**Comment by Piicharpa** [comment]
@SUPATKN เราคิดว่าเราแก้ bug ได้แล้วๆ ลองดูให้หน่อย
[https://scratch.mit.edu/projects/729042130](url)

**Comment by Piicharpa** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/110968305/188840734-0aa87269-4388-451c-9597-ae89f419ca20.png)

**Comment by SUPATKN** [comment]
เราว่าได้เลยนะแก้ได้ละ แต่ว่าถ้าเมาส์หลุดจออะมันจะหยุดอะมันทำให้ดูบังคับยากไปมั้ย หรือเราจะเปลี่ยนไปใช้คีย์บอร์ดหันเหมือนเดิมดี ?

**Comment by Piicharpa** [comment]
ถ้าใช้เม้าคือหมุนกับเดินพร้อมกันเลยปะ

**Comment by SUPATKN** [comment]
มันจะเมาหัวนะเราเคยลองละ ถ้าจะทำงั้นใช้คีย์บอร์ดอย่างเดียวไปเลยมั้ย ก็คือตัดเมาส์ไปเลย

**Comment by Piicharpa** [comment]
โอเค ถ้างั้นเอาแบบคีย์บอร์ดๆ

**Comment by SUPATKN** [comment]
โอเคๆงั้นเราแก้แปป
