### ISSUE TITLE
Item + Monster

### ISSUE THREAD

**Issue by Piicharpa** [Piicharpa/scratch-project-001#7]
Boom - Monster
Neuah - Item
Arm - design

**Comment by SUPATKN** [comment]
https://scratch.mit.edu/projects/727800996 เอาไปทำ monster ต่อได้เลยนะ

**Comment by ChonlakornBoom** [comment]
https://scratch.mit.edu/projects/729094664 ขอทำต่อพรุ้งนี้

**Comment by SUPATKN** [comment]
https://scratch.mit.edu/projects/729149004 จะทำต่อใช้อันนี้เลยนะ เราเพิ่มเติมไปละ + แก้ไขนิดหน่อย ถ้าจะทำต่อให้ไปที่นาที 25:43 ของคลิปนี้เลยนะ https://youtu.be/Q4cDDNCXfHA?t=1543 @ChonlakornBoom 
ที่เราเพิ่มไปก็คือทำให้ monster หลบด้านหลังกำแพงได้แล้วตามรูปเลย
![300231349_3355943524695379_3994281293810755663_n](https://user-images.githubusercontent.com/110968387/188936796-c19fce47-632d-4730-8176-b0bdc9cbdb5d.png)

**Comment by ChonlakornBoom** [comment]
https://scratch.mit.edu/projects/729254628 ทำถึง EP5 แต่มีBugตรงที่ ตัวละครไม่ยอมเปลี่ยน Type

**Comment by Piicharpa** [comment]
อันนี้คือเราเอาไปทำต่อได้เลยใช่มั้ย

**Comment by SUPATKN** [comment]
ได้เลยๆ

**Comment by SUPATKN** [comment]
https://youtu.be/swWi1ynPbdo อันนี้ลิ้ง ep5

**Comment by Piicharpa** [comment]
https://scratch.mit.edu/projects/729558901 อันนี้แก้บัค + item
