### ISSUE TITLE
Next level + Menu

### ISSUE THREAD

**Issue by Piicharpa** [Piicharpa/scratch-project-001#8]
Neuah - Next level
Yacht - Menu

**Comment by SUPATKN** [comment]
ตอนนี้เราเริ่มทำเมนูเกมละ หน้าเมนูมีเสียงก่อนกดเล่นด้วยแหละะ เดี๋ยวรอ design ทำเสร็จจะเอามาประกอบกันละเดี๋ยวส่งให้ดู

**Comment by SUPATKN** [comment]
https://scratch.mit.edu/projects/729578615 ตอนนี้ทำ menu ตอนเริ่มเกมกับตอนจบเกมละ (ตอนนี้เราใส่รูป demo ไปก่อนนะเดี๋ยวค่อยมาเปลี่ยน) วันนี้พอก่อนปวดหลัง5555

**Comment by kittisak101** [comment]
![manu](https://user-images.githubusercontent.com/110956091/189719750-451b182d-bb8d-4804-931b-9e38c3ebaab3.png)
จะให้เพิ่มอะไรก็บอกนะ

**Comment by kittisak101** [comment]
![a9a180ff-c84c-46dc-a34f-6a09edad2af3](https://user-images.githubusercontent.com/110956091/189909743-b1c20b27-72ce-461a-9f3b-9cea3af50f91.png)
