### ISSUE TITLE
Develop 

### ISSUE THREAD

**Issue by Piicharpa** [Piicharpa/scratch-project-001#9]

**Comment by Piicharpa** [comment]
อาจารย์เสนอเรื่องการติดเชื่อ คือ Monster อาจมีการไอก่อนติดเชื้อ
เราเสนอเรื่องการเพิ่มเสียง horror เข้าไป

**Comment by SUPATKN** [comment]
เราว่าจะเสนอถ้าเกมเสร็จ แบบด่าน 2,3 ที่ยากขึ้น น่าจะเพิ่มมอนเตอร์อีกแบบที่วิ่งเร็วขึ้น + แอบมี jumpscare

**Comment by SUPATKN** [comment]
ถ้าเดินเข้าประตูจะเล่นเสียงเปิดประตู เขียนไว้ก่อนกันลืม
